name: djs_live_stream

description: "djs_live_stream Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  intl: ^0.20.2
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  firebase_messaging: ^15.1.2
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^5.0.11
  sign_in_with_apple: ^6.1.0
  crypto: ^3.0.3
  cupertino_icons: ^1.0.8
  dio: ^5.4.3
  flutter_riverpod: ^2.5.1
  flutter_local_notifications: ^17.2.3
  image_picker: ^1.0.4
  agora_rtc_engine: ^6.2.3
  permission_handler: ^12.0.1
  wakelock_plus: ^1.1.1
  camera: ^0.11.1
  path_provider: ^2.1.2
  video_player: ^2.8.2
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.4
  just_audio: ^0.9.46
  just_audio_platform_interface: ^4.2.1
  audioplayers: ^5.2.1
  video_thumbnail: ^0.5.3
  flutter_svg: ^2.0.7
  visibility_detector: ^0.3.3
  json_annotation: ^4.8.1
  web_socket_channel: ^3.0.3
  qr_flutter: ^4.1.0
  image: ^4.1.3
  open_file: ^3.3.2
  share_plus: ^7.2.1
  url_launcher: ^6.2.5
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.1.0
  speech_to_text: ^7.2.0
  record: ^6.0.0
  package_info_plus: ^8.3.0
  mime: ^1.0.6
  path: ^1.9.0
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  characters: ^1.3.0
  collection: ^1.18.0
  pull_to_refresh_flutter3: ^2.0.2
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.3.1
  svgaplayer_flutter: ^2.2.0
  archive: ^3.4.10
  in_app_purchase: ^3.1.11
  in_app_purchase_storekit: ^0.3.6
  webview_flutter: ^4.7.0
  uuid: ^4.5.1

  fulive_plugin:
    path: third_party/fulive_plugin

dependency_overrides:
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/emojis/basic/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.jpeg"

flutter_native_splash:
  color: "#FFFFFF"                # 啟動背景色（可改）
  image: "assets/app_lunch.png"     # 啟動畫面顯示的圖片
  android: true
  ios: true
  web: false