name: djs_live_stream

description: "djs_live_stream Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  intl: ^0.20.2
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  google_sign_in: ^6.1.5
  cupertino_icons: ^1.0.8
  dio: ^5.4.3
  flutter_riverpod: ^2.5.1
  image_picker: ^1.0.4
  agora_rtc_engine: ^6.2.3
  permission_handler: ^12.0.1
  wakelock_plus: ^1.1.1
  camera: ^0.11.1
  path_provider: ^2.1.2
  video_player: ^2.8.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/demo_video.mp4