// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-ZNBIvGr9h6SSSxldhEOibEX7ls_WpEo',
    appId: '1:859186500950:web:e502dd2f99c37c282132f7',
    messagingSenderId: '859186500950',
    projectId: 'lu-live',
    authDomain: 'lu-live.firebaseapp.com',
    storageBucket: 'lu-live.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJyElaLgPJSLWE3mjA84Kb1-8NDUBfVOE',
    appId: '1:859186500950:android:32f7482d5af29a522132f7',
    messagingSenderId: '859186500950',
    projectId: 'lu-live',
    storageBucket: 'lu-live.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1voQfpf24F2e9_Sb0QdT6N4-NaAFsL7A',
    appId: '1:859186500950:ios:4375c9d36f2dd43c2132f7',
    messagingSenderId: '859186500950',
    projectId: 'lu-live',
    storageBucket: 'lu-live.firebasestorage.app',
    iosBundleId: 'lu.live',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1voQfpf24F2e9_Sb0QdT6N4-NaAFsL7A',
    appId: '1:859186500950:ios:65f711e61daf1acf2132f7',
    messagingSenderId: '859186500950',
    projectId: 'lu-live',
    storageBucket: 'lu-live.firebasestorage.app',
    iosBundleId: 'com.djs.live.djsLiveStream',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-ZNBIvGr9h6SSSxldhEOibEX7ls_WpEo',
    appId: '1:859186500950:web:62822f229005b0442132f7',
    messagingSenderId: '859186500950',
    projectId: 'lu-live',
    authDomain: 'lu-live.firebaseapp.com',
    storageBucket: 'lu-live.firebasestorage.app',
  );
}
